### ISSUE TITLE
Create a welcome book for new players

### ISSUE THREAD

**Issue by CrazyJMB** [CrazyJMB/minecraft-welcome-datapack#2]
# Description
Generate a welcome book that will be automatically given to new players when they first join the server.

# Tasks
- [x] Design the content of the welcome book, which may include information about server rules, getting started guide, useful links, etc.
- [x] Create a text file with the content of the book in JSON format compatible with Minecraft.
- [x] Develop a script within the datapack to grant the welcome book to the player upon joining the server for the first time.
- [x] Integrate the welcome book into the player login process to ensure automatic delivery.
- [x] Verify that the book is correctly delivered to new players and adjust as necessary.
- [x] Document the process of creating and configuring the welcome book for ease of maintenance and customization.
